# Generated by Django 4.2.9 on 2024-03-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='needs_projector',
        ),
        migrations.AddField(
            model_name='bookings',
            name='napomena',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
